---
- name: Deploy MetalLB
  hosts: master
  tasks:
    # Limpieza previa
    - name: Remove existing MetalLB installation
      shell: |
        kubectl delete namespace metallb-system --ignore-not-found=true
      ignore_errors: yes

    # Crear namespace
    - name: Create metallb namespace
      command: kubectl create namespace metallb-system
      ignore_errors: yes

    # Crear secret
    - name: Create memberlist secret
      shell: |
        kubectl create secret generic -n metallb-system memberlist \
        --from-literal=secretkey="$(openssl rand -base64 128)"
      ignore_errors: yes

    # Instalar MetalLB
    - name: Install MetalLB
      command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

    # Esperar a que los pods estén listos
    - name: Wait for MetalLB pods
      shell: |
        kubectl -n metallb-system wait --for=condition=ready pod --selector=app=metallb --timeout=90s
      register: wait_result
      until: wait_result.rc == 0
      retries: 30
      delay: 10

    # Configurar MetalLB
    - name: Configure MetalLB
      copy:
        dest: /tmp/metallb-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{ metallb_ip_range }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advert
            namespace: metallb-system
          spec:
            ipAddressPools:
            - first-pool

    - name: Apply MetalLB configuration
      command: kubectl apply -f /tmp/metallb-config.yaml

    # Verificar estado
    - name: Check MetalLB status
      shell: |
        echo "=== MetalLB Pods ==="
        kubectl get pods -n metallb-system
        echo "=== MetalLB Configuration ==="
        kubectl get ipaddresspools.metallb.io -n metallb-system
        kubectl get l2advertisements.metallb.io -n metallb-system
      register: metallb_status

    - name: Show MetalLB status
      debug:
        var: metallb_status.stdout_lines 