---
- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --apiserver-advertise-address={{ apiserver_advertise_address }}
    --ignore-preflight-errors=all
  register: kubeadm_init
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0644'

- name: Install Flannel CNI
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  
- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command_raw

- name: Store join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Include MetalLB tasks
  include_tasks: metallb.yml
  tags: 
    - metallb
  when: "'metallb' in ansible_run_tags"

- name: Remove master node taint
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  ignore_errors: yes

- name: Include NFS test tasks
  include_tasks: nfs-test.yml

- name: Include test deployment
  include_tasks: test-deployment.yml
  tags: 
    - test-deploy 

- name: Include Metrics Server tasks
  include_tasks: metrics-server.yml
  tags: 
    - metrics-server
  when: true  # Forzar la ejecución 

- name: Configure master node firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 6443/tcp    # Kubernetes API server
    - 2379-2380/tcp # etcd server client API
    - 10250/tcp   # Kubelet API
    - 10251/tcp   # kube-scheduler
    - 10252/tcp   # kube-controller-manager
  notify: reload firewall

- name: Allow worker nodes
  firewalld:
    rich_rule: "rule family=ipv4 source address={{ hostvars[item].ansible_host }}/32 accept"
    permanent: yes
    state: enabled
  loop: "{{ groups['workers'] }}"
  notify: reload firewall 