---
# Limpieza completa de MetalLB
- name: Remove existing MetalLB installation
  shell: |
    # Eliminar namespace y recursos
    kubectl delete namespace metallb-system --ignore-not-found=true
    # Eliminar webhooks
    kubectl delete validatingwebhookconfiguration metallb-webhook-configuration --ignore-not-found=true
    kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml --ignore-not-found=true
  ignore_errors: yes

- name: Wait for cleanup
  shell: |
    kubectl wait --for=delete namespace/metallb-system --timeout=60s
  ignore_errors: yes

# Instalación básica de MetalLB
- name: Create metallb namespace
  command: kubectl create namespace metallb-system

- name: Create memberlist secret
  shell: |
    kubectl create secret generic -n metallb-system memberlist \
    --from-literal=secretkey="$(openssl rand -base64 128)"

- name: Create basic MetalLB manifest
  copy:
    dest: /tmp/metallb-basic.yaml
    content: |
      # CRDs primero
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: ipaddresspools.metallb.io
      spec:
        group: metallb.io
        names:
          kind: IPAddressPool
          plural: ipaddresspools
          singular: ipaddresspool
        scope: Namespaced
        versions:
          - name: v1beta1
            served: true
            storage: true
            schema:
              openAPIV3Schema:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      addresses:
                        type: array
                        items:
                          type: string
      ---
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: l2advertisements.metallb.io
      spec:
        group: metallb.io
        names:
          kind: L2Advertisement
          plural: l2advertisements
          singular: l2advertisement
        scope: Namespaced
        versions:
          - name: v1beta1
            served: true
            storage: true
            schema:
              openAPIV3Schema:
                type: object
                properties:
                  spec:
                    type: object
                    properties:
                      ipAddressPools:
                        type: array
                        items:
                          type: string
      ---
      # Service Accounts
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller
        namespace: metallb-system
      ---
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: speaker
        namespace: metallb-system
      ---
      # RBAC
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: metallb-system:controller
      rules:
        - apiGroups: [""]
          resources: ["services"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["metallb.io"]
          resources: ["*"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: metallb-system:speaker
      rules:
        - apiGroups: [""]
          resources: ["services", "endpoints", "nodes"]
          verbs: ["get", "list", "watch"]
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: metallb-system:controller
      subjects:
        - kind: ServiceAccount
          name: controller
          namespace: metallb-system
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: metallb-system:controller
      ---
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: metallb-system:speaker
      subjects:
        - kind: ServiceAccount
          name: speaker
          namespace: metallb-system
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: metallb-system:speaker
      ---
      # Deployments
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: controller
        namespace: metallb-system
      spec:
        selector:
          matchLabels:
            app: metallb
            component: controller
        template:
          metadata:
            labels:
              app: metallb
              component: controller
          spec:
            containers:
            - name: controller
              image: quay.io/metallb/controller:v0.13.7
              args:
              - --port=7472
              ports:
              - containerPort: 7472
                name: monitoring
            serviceAccountName: controller
      ---
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: speaker
        namespace: metallb-system
      spec:
        selector:
          matchLabels:
            app: metallb
            component: speaker
        template:
          metadata:
            labels:
              app: metallb
              component: speaker
          spec:
            containers:
            - name: speaker
              image: quay.io/metallb/speaker:v0.13.7
              args:
              - --port=7472
              ports:
              - containerPort: 7472
                name: monitoring
            serviceAccountName: speaker
            hostNetwork: true

- name: Apply basic MetalLB manifest
  command: kubectl apply -f /tmp/metallb-basic.yaml

- name: Wait for MetalLB deployment
  shell: |
    kubectl -n metallb-system rollout status deployment controller
  register: controller_status
  retries: 30
  delay: 10
  until: controller_status.rc == 0

# Configuración de MetalLB
- name: Create MetalLB config
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - {{ metallb_ip_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
      spec:
        ipAddressPools:
        - first-pool

- name: Apply MetalLB configuration
  command: kubectl apply -f /tmp/metallb-config.yaml

- name: Show MetalLB status
  shell: |
    kubectl get pods -n metallb-system
  register: metallb_status 