---
# Limpieza completa de MetalLB
- name: Remove existing MetalLB installation
  shell: |
    # Eliminar namespace
    kubectl delete namespace metallb-system --ignore-not-found=true
    # Eliminar CRDs
    kubectl delete crd addresspools.metallb.io --ignore-not-found=true
    kubectl delete crd bfdprofiles.metallb.io --ignore-not-found=true
    kubectl delete crd bgpadvertisements.metallb.io --ignore-not-found=true
    kubectl delete crd bgppeers.metallb.io --ignore-not-found=true
    kubectl delete crd communities.metallb.io --ignore-not-found=true
    kubectl delete crd ipaddresspools.metallb.io --ignore-not-found=true
    kubectl delete crd l2advertisements.metallb.io --ignore-not-found=true
  ignore_errors: yes

- name: Wait for namespace deletion
  shell: |
    kubectl wait --for=delete namespace/metallb-system --timeout=60s
  ignore_errors: yes

# Verificar que Helm está instalado
- name: Check if Helm is installed
  command: which helm
  changed_when: false

# Instalación de MetalLB usando Helm
- name: Add Helm repo
  shell: |
    helm repo add metallb https://metallb.github.io/metallb
    helm repo update

- name: Install MetalLB via Helm
  command: |
    helm install metallb metallb/metallb \
      --create-namespace \
      --namespace metallb-system \
      --wait

- name: Wait for MetalLB pods
  shell: |
    kubectl -n metallb-system wait --for=condition=ready pod --selector=app.kubernetes.io/name=metallb --timeout=180s
  register: wait_result
  until: wait_result.rc == 0
  retries: 30
  delay: 10
  ignore_errors: yes

# Configuración de MetalLB
- name: Create MetalLB config
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - {{ metallb_ip_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
      spec:
        ipAddressPools:
        - first-pool

- name: Apply MetalLB configuration
  command: kubectl apply -f /tmp/metallb-config.yaml

- name: Verify MetalLB status
  shell: |
    kubectl get pods -n metallb-system -o wide
  register: metallb_status 