---
# Limpieza completa de MetalLB
- name: Remove existing MetalLB installation
  shell: |
    # Eliminar namespace y recursos
    kubectl delete namespace metallb-system --ignore-not-found=true
    kubectl delete -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml --ignore-not-found=true
    
    # Eliminar webhooks
    kubectl delete validatingwebhookconfiguration metallb-webhook-configuration --ignore-not-found=true
  ignore_errors: yes

- name: Wait for cleanup
  shell: |
    kubectl wait --for=delete namespace/metallb-system --timeout=60s
  ignore_errors: yes

# Instalación básica de MetalLB
- name: Create metallb namespace
  command: kubectl create namespace metallb-system

- name: Create memberlist secret
  shell: |
    kubectl create secret generic -n metallb-system memberlist \
    --from-literal=secretkey="$(openssl rand -base64 128)"

- name: Download MetalLB manifest
  get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
    dest: /tmp/metallb.yaml

- name: Remove webhook configurations from manifest
  shell: |
    sed -i '/---/q' /tmp/metallb.yaml

- name: Apply modified MetalLB manifest
  command: kubectl apply -f /tmp/metallb.yaml

- name: Wait for MetalLB pods
  shell: |
    kubectl -n metallb-system wait --for=condition=ready pod --selector=app=metallb --timeout=180s
  register: wait_result
  until: wait_result.rc == 0
  retries: 30
  delay: 10
  ignore_errors: yes

# Configuración de MetalLB sin webhooks
- name: Create MetalLB config
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: first-pool
        namespace: metallb-system
      spec:
        addresses:
        - {{ metallb_ip_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
      spec:
        ipAddressPools:
        - first-pool

- name: Apply MetalLB configuration
  shell: |
    kubectl apply -f /tmp/metallb-config.yaml --validate=false

- name: Verify MetalLB status
  shell: |
    kubectl get pods -n metallb-system -o wide
  register: metallb_status 