---
- name: Create metrics-server manifest
  copy:
    dest: /tmp/components.yaml
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metrics-server
        namespace: kube-system
      spec:
        selector:
          matchLabels:
            k8s-app: metrics-server
        template:
          metadata:
            labels:
              k8s-app: metrics-server
          spec:
            hostNetwork: true
            nodeName: k8s-master
            containers:
            - args:
              - --cert-dir=/tmp
              - --secure-port=4443
              - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
              - --kubelet-use-node-status-port
              - --metric-resolution=15s
              - --kubelet-insecure-tls
              command:
              - /metrics-server
              image: registry.k8s.io/metrics-server/metrics-server:v0.7.2
              name: metrics-server
              ports:
              - containerPort: 4443

- name: Deploy Metrics Server
  command: kubectl apply -f /tmp/components.yaml

- name: Verify deployment
  shell: |
    echo "=== Metrics Server Status ==="
    kubectl -n kube-system get pods -l k8s-app=metrics-server
    echo "\n=== Testing metrics ==="
    kubectl top nodes || echo "Waiting for metrics..." 