---
# Clonar y preparar la aplicación web en NFS
- name: Clone and setup web application
  shell: |
    cd {{ nfs_path }}
    rm -rf *  # Limpiar el directorio primero
    git clone https://github.com/salocin0430/COS_PHP_WEB.git
    mv COS_PHP_WEB/* .
    rm -rf COS_PHP_WEB
    # Ajustar permisos para Apache
    chown -R www-data:www-data {{ nfs_path }}
    chmod -R 755 {{ nfs_path }}
    find {{ nfs_path }} -type f -exec chmod 644 {} \;
    find {{ nfs_path }} -type d -exec chmod 755 {} \;
  delegate_to: nfs-server

# Desplegar la aplicación PHP
- name: Create PHP web deployment
  copy:
    dest: /tmp/php-webapp.yaml
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: php-webapp
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: php-webapp
        template:
          metadata:
            labels:
              app: php-webapp
          spec:
            securityContext:
              fsGroup: 33
            containers:
            - name: php-apache
              image: php:7.4-apache
              ports:
              - containerPort: 80
              volumeMounts:
              - name: webapp-volume
                mountPath: /var/www/html
              securityContext:
                runAsUser: 33  # www-data user ID
                runAsGroup: 33  # www-data group ID
            volumes:
            - name: webapp-volume
              persistentVolumeClaim:
                claimName: nfs-pvc-test
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: php-webapp-service
        annotations:
          metallb.universe.tf/address-pool: first-pool
      spec:
        type: LoadBalancer
        selector:
          app: php-webapp
        ports:
        - port: 80
          targetPort: 80

- name: Apply PHP deployment
  command: kubectl apply -f /tmp/php-webapp.yaml

- name: Wait for deployment
  shell: |
    kubectl rollout status deployment/php-webapp
  register: deployment_status
  until: deployment_status.rc == 0
  retries: 30
  delay: 10

- name: Get service IP
  shell: |
    kubectl get service php-webapp-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: service_ip
  until: service_ip.stdout != ""
  retries: 30
  delay: 10

- name: Show deployment information
  debug:
    msg: |
      PHP Web application has been deployed!
      You can access it at: http://{{ service_ip.stdout }}
      Try the matrix test at: http://{{ service_ip.stdout }}/matrix.php?size=400
      
      To see pod distribution:
      kubectl get pods -l app=php-webapp -o wide 