---
# Test de aplicación web con NFS y LoadBalancer
- name: Create test web deployment
  copy:
    dest: /tmp/test-web.yaml
    content: |
      # PersistentVolume para web
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: web-pv
      spec:
        capacity:
          storage: 1Gi
        accessModes:
          - ReadWriteMany
        persistentVolumeReclaimPolicy: Retain
        nfs:
          path: {{ nfs_path }}
          server: {{ hostvars['nfs-server'].ansible_host }}
      ---
      # PersistentVolumeClaim para web
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: web-pvc
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
      ---
      # Deployment de NGINX
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-nginx
      spec:
        replicas: 3
        selector:
          matchLabels:
            app: web-nginx
        template:
          metadata:
            labels:
              app: web-nginx
          spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
              volumeMounts:
              - name: web-content
                mountPath: /usr/share/nginx/html
            volumes:
            - name: web-content
              persistentVolumeClaim:
                claimName: web-pvc
      ---
      # Service tipo LoadBalancer
      apiVersion: v1
      kind: Service
      metadata:
        name: web-service
      spec:
        type: LoadBalancer
        ports:
        - port: 80
          targetPort: 80
        selector:
          app: web-nginx

- name: Apply test web deployment
  command: kubectl apply -f /tmp/test-web.yaml

- name: Create test web content
  shell: |
    mkdir -p /tmp/web-test
    cat > /tmp/web-test/index.html << EOF
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test K8s Cluster</title>
    </head>
    <body>
        <h1>Kubernetes Cluster Test</h1>
        <p>This page is served from NFS storage and exposed via MetalLB LoadBalancer</p>
        <p>Pod: \$(hostname)</p>
        <p>Time: \$(date)</p>
    </body>
    </html>
    EOF
    kubectl exec -it $(kubectl get pod -l app=web-nginx -o jsonpath='{.items[0].metadata.name}') -- sh -c "cp /tmp/web-test/* /usr/share/nginx/html/"

- name: Wait for deployment
  shell: |
    kubectl rollout status deployment/web-nginx
  register: deployment_status
  until: deployment_status.rc == 0
  retries: 30
  delay: 10

- name: Get service IP
  shell: |
    kubectl get service web-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
  register: service_ip

- name: Show test information
  debug:
    msg: |
      Web application has been deployed!
      You can access it at: http://{{ service_ip.stdout }}
      
      To test load balancing, try refreshing the page multiple times.
      You should see different pod names as the requests are distributed. 